### ISSUE TITLE
Add voyager jupyterlab extension to data science distribution

### ISSUE THREAD

**Issue by dkleissa** [gigantum/base-images#21]
https://github.com/altair-viz/jupyterlab_voyager

Voyager is a a JupyterLab MIME renderer extension to view CSV and JSON that might be useful for users who are exploring data.

**Comment by davclark** [comment]
See here for demo project: https://gigantum.com/tinydav/voyager-demo

It's pretty trivial - just a single RUN statement

I don't know how useful it is for collaborative work - as it doesn't save the view or logic, you can just save a Vega-lite JSON file. The UI is a little odd - you right click to open Voyager on a specific JSON or CSV file (or also to view w/ Vega, etc.).

**Comment by davclark** [comment]
I'm closing this for now. @dkleissa feel free to re-open.
