### ISSUE TITLE
Enable apt-key adv --recv-keys

### ISSUE THREAD

**Issue by davclark** [gigantum/base-images#27]
I'm not sure if this should be for all bases or not, but it's not uncommon to find instructions like the following (here to configure neurodebian):

```
RUN wget -O- http://neuro.debian.net/lists/bionic.us-tn.full | tee /etc/apt/sources.list.d/neurodebian.sources.list \
    && apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
```

This will require the packages `gpg`, `gpg-agent`, and `dirmngr` to be installed (can be done with `--no-install-recommends`). Installing this in minimal bases obviously conflicts with a desire to keep those bases small. But easy installation of random software seems important.

**Comment by dkleissa** [comment]
@davclark - I think for now this should just be covered via docker snippets. If a user really needs this they can. _Maybe_ in the future a more managed, advanced UI would be justified, but i think we need more data before doing that. I'm considering closing this vs. icebox. Thoughts?

**Comment by davclark** [comment]
Hard call. Neurodebian all by itself seems huge for the neuro crowd, which is our first easy target audience if we're serious about academics...

Perhaps a spectrum chat about this so at least there's somewhere for folks to find it and encourage discussion?

**Comment by dkleissa** [comment]
Ok. If you want to post a message that would be great. Going to move to icebox for now.

**Comment by davclark** [comment]
https://spectrum.chat/gigantum/general/installing-packages-securely-with-apt-apt-key-gpg-etc~4a7e1b64-d19f-4efd-9e9c-4052ac474431
