### ISSUE TITLE
Pin nodejs version

### ISSUE THREAD

**Issue by davclark** [gigantum/base-images#28]
Especially for the python3-minimal base, if we want to install nodejs, it will then require a rebuild for the jupyterlab extensions if the nodejs version doesn't match (which it won't now if you install latest 10.x).

If we pin this, then it's easier to install the same nodejs version. Maybe down the road we even have this as a single click option in the environment?

**Comment by dkleissa** [comment]
Not clear what you are describing here. We install nodejs, but use it just to build extensions and then uninstall it. You're saying if you then install nodejs yourself in a project it causes a problem?

**Comment by davclark** [comment]
Yes - if you have a node version mismatch, Jupyter asks the user to rebuild extensions. This will happen every time they start the container.

**Comment by davclark** [comment]
It seems current python3-data-science image is using nodejs 11.9.0 - which is probably not what we want (we should probably use LTS - 10.x)

**Comment by dkleissa** [comment]
@davclark - thoughts on this lingering ticket. I haven't organized it anywhere...are you maybe sorting this now during base update? Are we sure this is something relatively critical to do?
