### ISSUE TITLE
Filter out large blobs from history

### ISSUE THREAD

**Issue by davclark** [gigantum/base-images#33]
We seem to have acquired a large blob that dramatically expanded the repository size. This should be filtered and the history of this repo should be re-written. DO NOT merge to master until we implement gigantum/gigantum-client#1097.

**Comment by dkleissa** [comment]
We should probably wait until 1097 is in the while for a release or two as well. Moving cloning to the background will at least speed up startup a bit.

**Comment by dkleissa** [comment]
This doesn't seem to be needed now. We removed a couple big branches and the clone is down to ~3-4MB.
