### ISSUE TITLE
RStudio base displays sign-in page during testing

### ISSUE THREAD

**Issue by davclark** [gigantum/base-images#45]
Using either integration, or also the most recent stable release, RStudio selenium tests fail (at least on Linux) because they aren't going to the RStudio IDE - instead they are showing a sign-in page.

This does NOT appear to be a timing issue, as the behavior persists even after introducing a 10-second wait following initial start of RStudio dev tool.

**Comment by dkleissa** [comment]
I believe this has been resolved in prior updates.
